import Layout from "../components/Layout";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          {children}
          <Script
            src="https://kit.fontawesome.com/4ef8c63dd7.js"
            crossOrigin="anonymous"
          />
        </Layout>
      </body>
    </html>
  );
}
